### ISSUE TITLE
InspIRCd exits with the wrong code when exiting due to a config error

### ISSUE THREAD

**Issue by clinew** [inspircd/inspircd#1369]
```
frostsnow@test ~/inspircd $ inspircd --config /etc/inspircd/inspircd.conf
InspIRCd - Internet Relay Chat Daemon
For contributors & authors: See /INFO Output
InspIRCd Process ID: 19143
Your configuration contains a deprecated value: <module name="m_chanprotect.so"> - has been replaced with m_customprefix as of 3.0 (at /etc/inspircd/modules.conf:419)
Your configuration contains a deprecated value: <module name="m_halfop.so"> - has been replaced with m_customprefix as of 3.0 (at /etc/inspircd/modules.conf:822)
Your configuration contains a deprecated value: <options:cyclehosts> - has been replaced with m_hostcycle as of 3.0 (at /etc/inspircd/inspircd.conf:567)
Your configuration contains a deprecated value: <performance:nouserdns> - has been moved to <connect:resolvehostnames> as of 3.0 (at /etc/inspircd/inspircd.conf:666)
frostsnow@test ~/inspircd $ echo $?
0
```
Expected: Non-zero return code, especially 2 as per the documentation.

**Comment by SISheogorath** [comment]
Warnings are not an error when the IRCd runs in background exit code 0 is okay.

**Comment by clinew** [comment]
I ran it with `--nofork` and the exit code was 2.  I don't see how something that stops the daemon from actually running can be considered a "warning" and not an error.  Nonetheless, if exiting 0 is standard for post-daemonization failures I can accept that.

**Comment by SISheogorath** [comment]
When it prevents the deamon from running, means the forking in background fails, it should return a non-zero exit.

**Comment by clinew** [comment]
Now I'm confused.  A non-zero exit should only occur when the *forking* fails, correct?  And then subsequent failures will not return an error code.  I'll illustrate:

Scenario: ./inspircd --config /etc/inspircd/mybadconfig.conf
1.  User runs InspIRCd
2.  InspIRCd forks successfully
3.  Original program returns 0 exit
4.  InspIRCd reads bad config file
5.  InspIRCd dies, no PID file or log is created.

Now, I don't know what's standard practice for daemons, but it seems to me that one would want to read the configuration file before daemonizing, otherwise it won't know where to set up a log file or PID file to report to.

**Comment by SISheogorath** [comment]
well, your order is not correct. InspIRCd forks into background after reading and parsing the config. So in case of a config error the process will fail. in your case you see "deprecated warning" which shouldn't make anything fail.

once InspIRCd is started and forked into background it refuses to apply broken configs.

Maybe @SaberUK can explain some details.

What we maybe see here is a problem with the helper script. In case these deprecated warnings should result in an error.

**Comment by clinew** [comment]
When I remove the deprecated warnings, the program works fine, so it seems to me that the deprecation warnings are resulting in an error.  I'm going to reopen this until we can figure out what's going on.

**Comment by SadieCat** [comment]
I think this should be resolved in Git master.

**Comment by clinew** [comment]
InspIRCd still fails on a bad configuration file **post**-daemonizing.  The result is that a bad configuration file cannot be detected by checking the binary's exit status; instead the failure must be inferred by the lack of a PID file (or some other method).  This may or may not be the intention.

```
$ ./build/GCC-12.3/bin/inspircd --nofork
InspIRCd - Internet Relay Chat Daemon
See /INFO for contributors & authors
					  
InspIRCd Process ID: 2100
Syntax error - start of tag expected at /etc/inspircd/inspircd.conf:489:11 (last
tag was on line 394)
$ echo $?
1 
```

```
$ ./build/GCC-12.3/bin/inspircd         
InspIRCd - Internet Relay Chat Daemon
See /INFO for contributors & authors
		   
InspIRCd Process ID: 2102
Syntax error - start of tag expected at /etc/inspircd/inspircd.conf:489:11 (last
tag was on line 394)
$ echo $?
0 
```

Tested against `v4.0.0a23`.

**Comment by satmd** [comment]
Would it be helpful if inspircd would check the config before forking?

I see `src/inspircd.cpp`  lines 501-510 and wonder if this could be done by rearranging the calls in 509-510 just before 501.

**Comment by clinew** [comment]
Fix confirmed, thank you!
